### PR TITLE
Fix mdox-gen-exec issues with --help commands

### LINKED ISSUE #10: `mdox-gen-exec` Make it easier to use with --help
Usually  --help returns non 0 exit code. This fails to format.

Workaround like ````bash mdox-gen-exec="sh -c 'bingo --help || exit 0'"` works but it's ugly.

Wonder if we can improve the experience somehow.

### PR DESCRIPTION
**Pull request by saswatamcode**
This PR fixes the issue where commands with non 0 exit codes (usually `--help` commands) fail to format. Fixes #10 
Before this fix, the markdown below results in an error,
```
```bash mdox-gen-exec="go --help"
.
.
.
error:  first formatting phase for /Users/saswatamukherjee/web/mdox/test.md: run go --help: exit status 2
``` 
A workaround is using something like `mdox-gen-exec="sh -c 'go --help || exit 0'"` but this is not preferable. 
With this fix, a flag can be passed to allow non zero exit codes to format successfully, like below, 
```
```bash mdox-nonzero-exit-code mdox-gen-exec="go --help"
Go is a tool for managing Go source code.

Usage:

	go <command> [arguments]
...
```
This would also be suitable in case an error code block example needs to be generated.

### CODE REVIEW

File: pkg/mdformatter/mdgen/mdgen.go [hunk 1]
```diff
@@ -19,6 +19,7 @@ const (
 	infoStringKeyLang = "mdox-gen-lang"
 	infoStringKeyType = "mdox-gen-type"
 	infoStringKeyExec = "mdox-gen-exec"
+	skipExitCodeCheck = "mdox-nonzero-exit-code"
```
Comment (bwplotka) [inline pkg/mdformatter/mdgen/mdgen.go:22]: I wonder... should we just don't care about exit codes? 🤔

Comment (bwplotka) [reply pkg/mdformatter/mdgen/mdgen.go:22]: Also variable name is not telling the same as string

**Review by bwplotka — COMMENTED** [review]
Epic work, thanks!

Wonder... what would be the best experience here. Some suggestions:

1. What about opposite: have option `expect-exit-code` = `2` and by default don't check exit code?
2. Can we run quick test to ensure this? 🤗

File: pkg/mdformatter/mdgen/mdgen.go (hunk 1 above)
Comment (saswatamcode) [reply pkg/mdformatter/mdgen/mdgen.go:22]: Initially, I did think that not checking for exit codes would be better, but then user wouldn’t be able to tell which command in a md code block had an actual error and that might get formatted without the user noticing. For eg `npm —versionn` is a typo which would come up as an error if we check the exit code. However, if we skip that then something entirely different than the version number might get formatted.
Would the better option be to have an `expect-exit-code` flag which will be matched if non 0 exit code occurs?

Comment (bwplotka) [reply pkg/mdformatter/mdgen/mdgen.go:22]: I think tag makes sense more like you did.

So what about by default expecting status code 0, but allow `expect-exit-code=X` to change that? 🤗

Comment (saswatamcode) [reply pkg/mdformatter/mdgen/mdgen.go:22]: Yup! That would be best. Implementing that along with a quick test! 😊

File: pkg/mdformatter/mdgen/mdgen.go [hunk 2]
```diff
@@ -16,9 +17,10 @@ import (
 )
 
 const (
-	infoStringKeyLang = "mdox-gen-lang"
-	infoStringKeyType = "mdox-gen-type"
-	infoStringKeyExec = "mdox-gen-exec"
+	infoStringKeyLang     = "mdox-gen-lang"
+	infoStringKeyType     = "mdox-gen-type"
+	infoStringKeyExec     = "mdox-gen-exec"
+	infoStringKeyExitCode = "expect-exit-code"
```
Comment (bwplotka) [inline pkg/mdformatter/mdgen/mdgen.go:23]:
```suggestion
	infoStringKeyExitCode = "mdox-expect-exit-code"
```

File: pkg/mdformatter/mdgen/mdgen.go [hunk 3]
```diff
@@ -38,12 +40,12 @@ func (t *genCodeBlockTransformer) TransformCodeBlock(ctx mdformatter.SourceConte
 	}
 	infoStringAttr := map[string]string{}
 	for i, field := range infoFiels {
-		if val := strings.Split(field, "="); val[0] == infoStringKeyLang || val[0] == infoStringKeyType || val[0] == infoStringKeyExec {
+		if val := strings.Split(field, "="); val[0] == infoStringKeyLang || val[0] == infoStringKeyType || val[0] == infoStringKeyExec || val[0] == infoStringKeyExitCode {
```
Comment (bwplotka) [inline pkg/mdformatter/mdgen/mdgen.go:43]: Time for some `switch` here (:

File: pkg/mdformatter/mdgen/mdgen.go [hunk 4]
```diff
@@ -38,12 +40,12 @@ func (t *genCodeBlockTransformer) TransformCodeBlock(ctx mdformatter.SourceConte
...
 			if i == 0 {
 				return nil, errors.Errorf("missing language info in fenced code block. Got info string %q", string(infoString))
 			}
 			if len(val) != 2 {
-				return nil, errors.Errorf("got %q without variable. Expected format is e.g ```yaml %q=<value> %q=<value2> . Got info string %q", val[0], infoStringKeyLang, infoStringKeyType, string(infoString))
+				return nil, errors.Errorf("got %q without variable. Expected format is e.g ```yaml %q=<value> %q=<value2> %q=<value2>. Got info string %q", val[0], infoStringKeyLang, infoStringKeyExitCode, infoStringKeyType, string(infoString))
```
Comment (bwplotka) [inline pkg/mdformatter/mdgen/mdgen.go:48]: same here

**Review by bwplotka — APPROVED** [review]
Amazing, looks good. Just some suggestions still.

**Review by bwplotka — COMMENTED** [review]
Nice, thanks!

LGTM 💪🏽
